"""add verification table

Revision ID: 4b6b4dd9e10b
Revises: 4476f877dd0f
Create Date: 2025-08-16 16:46:44.933663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b6b4dd9e10b"
down_revision: str | Sequence[str] | None = "4476f877dd0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    op.create_table(
        "verification",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("equipment_id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("verification_date", sa.Date(), nullable=False),
        sa.Column("interval_months", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_verification_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification")),
        sa.UniqueConstraint("equipment_id", name="uq_verification_equipment"),
    )
    op.create_index(
        op.f("ix_verification_equipment_id"),
        "verification",
        ["equipment_id"],
        unique=False,
    )

    op.alter_column(
        "equipment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "equipment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "equipment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "equipment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_verification_equipment_id"), table_name="verification")
    op.drop_table("verification")
    # ### end Alembic commands ###
