"""add equipment.state

Revision ID: ee8ed682d374
Revises: 4b6b4dd9e10b
Create Date: 2025-08-18 07:36:47.046920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8ed682d374"
down_revision: str | Sequence[str] | None = "4b6b4dd9e10b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment",
        sa.Column("state", sa.String(length=20), server_default="в работе", nullable=False),
    )
    op.create_index(op.f("ix_equipment_state"), "equipment", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_equipment_state"), table_name="equipment")
    op.drop_column("equipment", "state")
    # ### end Alembic commands ###
